# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php81:
    docker:
      - image: circleci/php:8.1-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction
      - run: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text
      - run: composer test
workflows:
  version: 2
  build:
    jobs:
      - php81