# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php80:
    docker:
      - image: circleci/php:8.0-cli-node-browsers
    steps:
      - checkout
      - run: sudo apt update -y
      - run: sudo apt install -y libyaml-dev
      - run: sudo pecl channel-update pecl.php.net
      - run: sudo pecl install yaml
      - run: sudo docker-php-ext-enable yaml
      - run: php -v
      - run: composer install --no-interaction
      - run: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-text
      - run: composer test
workflows:
  version: 2
  build:
    jobs:
      - php80